app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
		path('self-assessment/', views.self_assessment, name='self-assessment'),
		
]

sebelumpergi/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('main.urls')),
	path('', include('app.urls')),

]

app/templates/self-assessment.html
{% extends "base.html" %}
{% load static %}

{% block title %}self-assessment | SebelumPergi{% endblock %}

{% block content %}
	<div class="container">
		<h2 class="data judulself">Covid-19 Self-Assessment</h2>
		<div>
			<form class="data" action="{% url 'app:self-assessment' %}" method="POST" novalidate>{% csrf_token %}
        		{% for field in generate_form_demografi %}
        		<br>
        		<br>
            		{{ field.label_tag }} {{ field }}
        		{% endfor %}
        		{% for field in generate_form_high %}
        		<br>
        		<br>
            		{{ field.label_tag }} {{ field }}
        		{% endfor %}
        		{% for field in generate_form_medium %}
        		<br>
        		<br>
            		{{ field.label_tag }} {{ field }}
        		{% endfor %}
        		{% for field in generate_form_low %}
        		<br>
        		<br>
            		{{ field.label_tag }} {{ field }}
        		{% endfor %}
					<div class="data d-flex flex-column flex-md-row flex-wrap justify-content-center">
						<div class="col-2 buttontest">
							<button type="submit" class="btn btn-primary rounded-pill mt-3" name='simpan' value="Save">Submit</button>
						</div>
					</div>
			</form>
		</div>
	</div>
</body>
</html>

{% endblock %}